title: Laird Lonergan
description: Personal website of Laird Lonergan
email: me@sillylaird.ca
baseurl: ""
url: "https://sillylaird.ca"

# Build settings
markdown: kramdown
permalink: pretty
sass:
  style: compressed

# Custom theme settings
theme_color: "#4a86e8"
font_family: "Roboto, sans-serif"

# Navigation
navigation:
  - title: Home
    url: /
  - title: About
    url: /detailed-about/
  - title: Blog
    url: /Blog/
  - title: Rhythm Games
    url: /rhythm-games/